server:
  port: 9091
#server:
 # port: 9120
spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: ${manageproxyms.datasource.url:jdbc:h2:mem:manageproxymsDb;DB_CLOSE_DELAY=-1}
    username: ${manageproxyms.datasource.username:sa}
    password: ${manageproxyms.datasource.password:}
    driver-class-name: ${manageproxyms.datasource.driver:org.h2.Driver}
  jpa:
    show-sql: true
      

management:
  endpoints:
    web:
      exposure:
        include: "*"

        


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
        timeout:
          enabled: false     
          
jwtSecret: mySecretKey
jwtExpirationMs: 86400000
    

